---
title: "data_tidy"
output: github_document
---
```{r}
library(tidyverse)
```

## pivot_longer

load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

wide format to long format..
```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visits",
    names_prefix = "bd_score_",
    values_to = "bdi")
```
Rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visits",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% 
  relocate(id, visits) %>% 
  mutate(visits = recode(visits, "bl" = "00m"))

pulse_data
```

## pivot wider

make up some data

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatmnet", "placebo","placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "mean"
  )
```









